USE SimpleQuery
GO

-- INNER JOIN kiểu cũ
SELECT dbo.GIAOVIEN.HOTEN,dbo.BOMON.TENBM
FROM dbo.GIAOVIEN,dbo.BOMON
WHERE dbo.GIAOVIEN.MABM = dbo.BOMON.MABM

-- inner join kiểu mới 
-- có thể viết tắt INNER JOIN thành JOIN
SELECT dbo.GIAOVIEN.HOTEN,dbo.BOMON.TENBM
FROM dbo.GIAOVIEN INNER JOIN dbo.BOMON
ON BOMON.MABM = GIAOVIEN.MABM